// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfTMrPsBev528t-PpQJLgWv0KP_CChQxo',
    appId: '1:859654661318:web:e58d52f5457f8ad1df63c7',
    messagingSenderId: '859654661318',
    projectId: 'apps-333c0',
    authDomain: 'apps-333c0.firebaseapp.com',
    storageBucket: 'apps-333c0.firebasestorage.app',
    measurementId: 'G-KHLL896FZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8cuNz8ZiBBYSVbDKY-Bj9ben65s_eNG0',
    appId: '1:859654661318:android:c64a5b9caecdfa87df63c7',
    messagingSenderId: '859654661318',
    projectId: 'apps-333c0',
    storageBucket: 'apps-333c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD65sASgk7tD5YwU7qg5VmCK7-AWn6phYM',
    appId: '1:859654661318:ios:11628e42cc2c1d32df63c7',
    messagingSenderId: '859654661318',
    projectId: 'apps-333c0',
    storageBucket: 'apps-333c0.firebasestorage.app',
    iosBundleId: 'com.example.saudeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD65sASgk7tD5YwU7qg5VmCK7-AWn6phYM',
    appId: '1:859654661318:ios:11628e42cc2c1d32df63c7',
    messagingSenderId: '859654661318',
    projectId: 'apps-333c0',
    storageBucket: 'apps-333c0.firebasestorage.app',
    iosBundleId: 'com.example.saudeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfTMrPsBev528t-PpQJLgWv0KP_CChQxo',
    appId: '1:859654661318:web:46c2f5f5b0be9443df63c7',
    messagingSenderId: '859654661318',
    projectId: 'apps-333c0',
    authDomain: 'apps-333c0.firebaseapp.com',
    storageBucket: 'apps-333c0.firebasestorage.app',
    measurementId: 'G-65TTY14G00',
  );
}
